---
title: "R Notebook"
output: html_notebook
---


```{r}
library(tidyverse)

#Predictions from Hypomap
Human_hmpredictions = readRDS("~/Dropbox/Columbia/predictions_refined.rds")
#Kim_hmpredictions = readRDS("~/Dropbox/Columbia/predictions_Kim.rds")
#Romanov_hmpredictions = readRDS("~/Dropbox/Columbia/predictions_Romanov.rds")

CompilePredictions = as.data.frame(matrix(ncol = 0, nrow = dim(Human_hmpredictions$Dataset)[1]))
row.names(CompilePredictions) = row.names(Human_hmpredictions$Dataset)
for(x in names(Human_hmpredictions)){
Human_hmpredictions_Data = subset(Human_hmpredictions[[x]], Human_hmpredictions[[x]]$prediction.score.max >= 0.3)
Human_hmpredictions_Data2 = Human_hmpredictions_Data %>% dplyr::select(predicted.id)
colnames(Human_hmpredictions_Data2) = x
CompilePredictions = merge(CompilePredictions, Human_hmpredictions_Data2, by = 0, all = T)  
row.names(CompilePredictions) = CompilePredictions$Row.names; CompilePredictions$Row.names = NULL
}


#Iterative Analysis
MRTreeRes = readRDS("~/Dropbox/LabMac/tree80_L15_treeTrim.rds")
Resolutions = as.data.frame(MRTreeRes)
Resolutions$K560 = gsub(558, 11, gsub(554, 544, gsub(551, 348,  Resolutions$K560)))
Resolutions$K494 = gsub(508, 29,  Resolutions$K494)
Resolutions$Barcodes = row.names(Resolutions)

K560_Annots = read.csv("~/Dropbox/LabMac/Adult_CellTypeAssigns.csv")
K560_Annots = K560_Annots %>% dplyr::select("K560", "Class_K560", "ClassMarkers_K560", "Nuclei_K560", "NucleiMarkers_K560")
IterativeAnalysis = merge(K560_Annots, Resolutions, by = "K560")


#Trajectory Analysis
MainAssign = read.csv("~/Dropbox/LabMac/Fig2_Trajectories_GLOTMP_17JAN_20_20_3_k100AssignsByBarc.csv", na.strings=c("","NA"))
TrajectoryAssigns = MainAssign %>% dplyr::select(Nuclei)
row.names(TrajectoryAssigns) = MainAssign$Barcs

for(LIN in c("3_k20", "3_k150", "6_k100")){ #, ))
AltAssign = read.csv(paste("~/Dropbox/LabMac/Fig2_Trajectories_GLOTMP_17JAN_20_20_", LIN, "AssignsByBarc.csv", sep=""), na.strings=c("","NA"))
AltAssign2 = AltAssign %>% dplyr::select(Nuclei)
row.names(AltAssign2) = AltAssign$Barcs
AltName = ifelse(LIN == "3_k20", "Alt1", "")
AltName = ifelse(LIN == "3_k150", "Alt2", AltName)
AltName = ifelse(LIN == "6_k100", "Alt3", AltName)
colnames(AltAssign2) = paste(colnames(AltAssign2), AltName, sep="_")
TrajectoryAssigns = merge(TrajectoryAssigns, AltAssign2, by = 0, all = T)
row.names(TrajectoryAssigns) = TrajectoryAssigns$Row.names
TrajectoryAssigns$Row.names = NULL
}


CompileAll = merge(IterativeAnalysis, TrajectoryAssigns, by.x = "Barcodes", by.y = 0, all = T)
CompileAll = merge(CompileAll, CompilePredictions, by.x = "Barcodes", by.y =  0, all = T)
CompileAll[is.na(CompileAll)] = "NA"

CompileNucleiAnnotations = as.data.frame(matrix(ncol = 9, nrow = 0))
colnames(CompileNucleiAnnotations) = c("IterClust", "IterNuc", "MainTraj_Nuclei", "Alt1Traj_Nuclei", "Alt2Traj_Nuclei", "Alt3Traj_Nuclei", "HypoMap_Dataset", "HypoMap_RegionPredicted",  "HypoMap_RegionSummarized")


for(x in sort(unique(CompileAll$K560))){
PullData = subset(CompileAll, CompileAll$K560 == x)  
Compile = list("IterClust" = x, "IterNuc" = unique(PullData$Nuclei_K560))
for(y in c("Nuclei", "Nuclei_Alt1", "Nuclei_Alt2", "Nuclei_Alt3", "Dataset", "Region_predicted", "Region_summarized")){
Tabulate = as.data.frame(table(PullData[[y]]))
Tabulate = Tabulate[order(-Tabulate$Freq), ]
Compile[[y]] = as.character(paste(paste(Tabulate$Var1, " [", round(Tabulate$Freq/dim(PullData)[1]*100, digits = 2), "%]", sep=""), collapse = "; "))
}
CompileRow = as.data.frame(t(unlist(c(Compile))))
colnames(CompileRow) = c("IterClust", "IterNuc", "MainTraj_Nuclei", "Alt1Traj_Nuclei", "Alt2Traj_Nuclei", "Alt3Traj_Nuclei", "HypoMap_Dataset", "HypoMap_RegionPredicted",  "HypoMap_RegionSummarized")
CompileNucleiAnnotations = rbind(CompileNucleiAnnotations, CompileRow)
}

write.csv(CompileNucleiAnnotations, "CompileNucleiAnnotations.csv", row.names = F)
```




```{r}
HumHyMaDev = readRDS("~/Dropbox/Columbia/HypoMapHUMANDev.rds")
HumHyMaDev@meta.data$DatasetClean = gsub("Affinati10x", "Affinati [Mouse Adult VMH]", gsub("Anderson10x", "Liu  [Mouse Adult VMH]", gsub("CampbellDropseq", "Campbell [Mouse Adult ARC]", gsub("ChenDropseq", "Chen [Mouse Adult]", gsub("Dowsett10xnuc", "Dowsett [Mouse Adult Hindbrain]", gsub("Flynn10x", "Mickelsen [Mouse Adult VPH]", gsub("Herb", "Herb [Human Fetal]", gsub("Kim10x", "Kim [Mouse Adult VMH]", gsub("KimDev", "Kim [Mouse Development]", gsub("LeeDropseq", "Lee [Mouse Adult]", gsub("Mickelsen10x", "Mickelsen [Mouse Adult LH]", gsub("Moffit10x", "Moffit [Mouse Adult PO]", gsub("Morris10x", "Morris [Mouse Adult SCN]", gsub("Mousebrainorg10x", "Zeisel [Mouse Adult]", gsub("RomanovDev", "Romanov [Mouse Development]", gsub("RossiDropseq", "Rossi [Mouse Adult LH", gsub("Rupp10x", "Rupp [Mouse Adult Lepr+]", gsub("Siletti", "Siletti [Human Adult]", gsub("Wen10x", "Wen [Mouse Adult SCN]", gsub("wenDropseq", "Wen [Mouse Adult SCN]", gsub("Zhou", "Zhou [Human Fetal]", HumHyMaDev@meta.data$Dataset)))))))))))))))))))))

HumHyMaDev = RunHarmony(HumHyMaDev, group.by.vars = "DatasetClean")
HumHyMaDev = RunUMAP(HumHyMaDev, reduction = "harmony", dims = 1:30)

DimPlot(HumHyMaDev, group.by = "DatasetClean", raster = T)

HypoMapHUMAN@meta.data$Dataset = ifelse(HypoMapHUMAN@meta.data$sample %in% c("GW22T_hypo1", "GW25_3V_hypo", "GW20_34_hypo","GW19_hypo", "CS22_2_hypo", "CS22_hypo", "GW18_hypo", "GW16_hypo"), "Herb_HumanFetal", HypoMapHUMAN@meta.data$Dataset)
HypoMapHUMAN@meta.data$Dataset = ifelse(HypoMapHUMAN@meta.data$sample %in% c("GW10", "GW12_01", "GW12_02", "GW15_A", "GW15_M", "GW15_P", "GW18_A", "GW18_Lane1", "GW18_Lane2", "GW18_Lane3", "GW18_M", "GW18_P", "GW20_A", "GW20_M", "GW20_P"), "Zhou_HumanFetal", HypoMapHUMAN@meta.data$Dataset)
                    
```

